### ISSUE TITLE
Drive away from geofence trigger door open. 

### ISSUE THREAD

**Issue by betatester88** [brchri/tesla-geogdo#13]
Hello Brchri,
Not sure if this is really a bug or a combination of other stuff.  This is 2nd time I have experienced this.  I rarely have my car parked on the driveway while the door is closed or close via other method before I pull out away from defined geofence. 

Environment: Car is on wifi within the range of home AP.  While pulling away from the house, it might have lost the connectivity or temporarily disconnected due to weak signal. 

Test scenario
v1.0.0
Garage Door open while car parked on driveway within geofence.
Close garage door via other method (myQ, or remote). - Forgot my car was in "park" or "reverse" (in case this may affect the live feed to teslamate).
Car pulled out of driveway away from geofence, door start to open.

This is when I drive AWAY from my geofence
12/21/2023 16:56:09 [INFO   ] Attempting to open garage door for car 1 at lat xx.xx3151, long -xx.xx6600 (redacted)
12/21/2023 16:56:09 [INFO   ] setting garage door open
12/21/2023 16:56:17 [INFO   ] Garage door state has been set successfully: open

Realized the door open
Close door via other method (MyQ)
Drive back to my driveway to check on the door (thought the default timeout was 5 mins ?)
This is when I drive into geofence (note the time from last action: open).
12/21/2023 16:58:39 [INFO   ] Attempting to open garage door for car 1 at lat xx.xx3281, long -xx.xx6623 (redacted)
12/21/2023 16:58:39 [INFO   ] setting garage door open
12/21/2023 16:58:46 [INFO   ] Garage door state has been set successfully: open

Here is my config: Note: I only have 'open' defined.
global:
  teslamate_mqtt_settings: # settings for teslamate's mqtt broker
    connection:
      host: 192.168.2.11 # dns, container name, or IP of teslamate's mqtt host
      port: 1883
      client_id: tesla-geogdo # optional, arbitrary client name for MQTT connection; must not be the same as any other MQTT client name, will use random uuid if omitted
      user: UserID 
      pass: mysecretpass 
      use_tls: false 
      skip_tls_verify: false 
  #cooldown: 5 # minutes to wait after operating garage before allowing another garage operation (set to 0 or omit to disable)

garage_doors:
  - geofence:
      type: polygon
      settings:
        open:
	- lat: xx.xxxxx
	  lng: xx.xxxxx
	....
	......
	
![geofence](https://github.com/brchri/tesla-geogdo/assets/24643405/94cacfc9-f1ed-40b2-998d-2f8e56d189d5)

**Comment by brchri** [comment]
Hi @betatester88. I have a hunch on what is happening here. the tl;dr is that I think you're running into a niche bug that would only be experienced by someone using _only_ an open geofence, and if it's what I think it is, I know how to fix it.

The longer version:

First, to address your question about the default cooldown - it's only 5 seconds, which is to prevent flapping. Since you have the cooldown line commented out in your config, after 5 seconds your door is eligible for operation again.

Now for your issue, which coincidentally is somewhat related to the cooldown. Lat and lng are published independently to the MQTT broker, and so the app checks every time it receives either one. However, this can be slightly inaccurate, because if you move, both lat and lng will _usually_ both be updated as a pair to the new point; however, let's say the lat is published first. It will pair the _new_ lat with the _old_ lng, which puts your location at a slightly incorrect position, since your new lat _should_ be paired with your new lng, but the new lng hasn't been processed yet.

In this scenario, the app incorrectly puts you just outside your geofence. Then when the corresponding lng gets processed, it pairs it correctly with the lat already received, giving your true position of being still inside the geofence. This causes a minor flap effect where it looks to the app like you teleported out of the geofence and back in, meaning it thinks it should trigger an open operation.

I experimented with only processing location updates after both lat and lng had been published, but teslamate doesn't always publish both. For example, if you're moving directly east or west, then your latitude is not changing, so only longitude gets published, and these events still need to be processed. Unfortunately there's no good way to determine if a lat/lng should be processed individually or if it should wait for its partner, as the partner may never arrive.

To fix this, I implemented the default 5s cooldown, but it only works for users with both open and closed geofences defined, for reasons that probably aren't worth explaining here. So I need to rework that logic a bit to handle cases like yours where just one geofence is being used.

I'll try and get an update published in the next day or two. Apologies for the bug; hopefully I'm right about what the problem is and it will fix it.

**Comment by betatester88** [comment]
No need for apologies and thank you for your work.  You continue to impress me :).  BTW, I just pulled the new image v2.0.  Will see tomorrow how things go.

**Comment by brchri** [comment]
Did you note the breaking changes? You'll need to update your config file for v2.

**Comment by betatester88** [comment]
Yes, I did modify the config, was able to start without error.

```
global:
  tracker_mqtt_settings: # Teslamate
    connection:
      host: 192.168.2.11 # dns, container name, or IP of tracker mqtt host
      port: 1883
      client_id: tesla-geogdo
      user: userID
      pass: Mysecret
      use_tls: false
      skip_tls_verify: false
  cooldown: 10 # minutes to wait after operating garage before allowing another garage operation (set to 0 or omit to disable)

garage_doors:
  - # main garage example
    geofence: 
      type: polygon
      settings:
        open_trigger: # define which geofence changes trigger a close action (e.g. moving from `home` geofence to `not_home`)
        - lat: xx.xx3085254219 (redacted)
          lng: -xx.xx6621008477 (redacted)
        - lat: xx.xx307616271 (redacted)
          lng: -xx.xx654427106 (redacted)
        - lat: xx.xx319517868 (redacted)
          lng: -xx.xx65185761 (redacted)
        - lat: xx.xx31918726 (redacted)
          lng: -xx.xx63973935 (redacted)
     opener:  # defines how to control the garage
      type: mqtt # type of garage door opener to use
      settings:
        connection:
          host: io.adafruit.com #for adafruit
          port: 8883
          user: IO_UserID 
          pass: IO_password 
          use_tls: true 
          skip_tls_verify: true
          client_id: tesla-geogdo-mqtt-opener
          # WARNING!! client_id's MUST BE UNIQUE for any mqtt client that shares a broker !!
        topics: # list of topics to subscribe to for status updates
          prefix: IO_UserID #adafruit uses UserID as prefix
          door_status: feeds/garagedoor_status 
          #obstruction: status/obstruction
          #availability: status/availability
        commands: # commands to operate the smart garage door opener
          - name: open
            payload: open
            topic_suffix: feeds/garage_cmd
            required_start_state: closed
            required_finish_state: open
          - name: close
            payload: close
            topic_suffix: feeds/garage_cmd
            required_start_state: open
            required_finish_state: closed
    trackers: 
      - id: 1 # required, some identifier, can be number or string
        lat_topic: teslamate/cars/1/latitude # topic to retrieve latitude for tracker
        lng_topic: teslamate/cars/1/longitude # topic to retrieve longitude for tracker
```

**Comment by brchri** [comment]
Nice, yeah looks good.

Okay I've pushed what is hopefully a fix for your issue, if you're interested in testing it out (not sure how reliably you could reproduce the issue before). The docker tag for the branch is `brchri/tesla-geogdo:add-delay-fix-flap`. If you decide to test, let me know how it goes!

**Comment by betatester88** [comment]
That was quick, thank you.  I just pulled it, the hard part is testing it since I don't get the issue most of the time with v1.
org.opencontainers.image.version | add-delay-fix-flap

**Comment by brchri** [comment]
Yeah I figured as much. Just run it for a bit if you don't mind and let me know if it happens again, you don't need to go out of your way to try to trigger it. If you go a week or more with no issues, we'll hope that it did indeed solve the problem and I'll merge it and release it.

**Comment by betatester88** [comment]
@brchri , Happy New Year. Just fyi, so far so good with "add-delay-fix-flap".  Haven't seen the issue yet, at the very least I haven't seen any negative impact.

**Comment by brchri** [comment]
Excellent, thanks for the update. I'll give it a full week before merging it into the main branch and publishing a release, but good to know that so far so good. 👍

**Comment by betatester88** [comment]
@brchri , Just want to give an update.  I think we are good, haven't had the issue for the last 2 + weeks.
